@startuml

package "Game System" {
    [Player] 
    [UI]
    [GameState]
    [Input]

    [Player] --> [UI] : Interacts with & \n Responds to
    [Input] --> [GameState] : Updates
    [UI] --> GameState : Displays
    [Player] --> [Input] : Controls
}

@enduml
