name: Movement Test
run-name: ${{ github.actor }} is testing out the Movemnet System 🚀
on: [push]
jobs:
  Movement-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      - name: Test Movemnet
        run: gradle test --tests "Movement"

